// The only door between the UI and the backend. MODE 'demo' answers from seeded data + the
// reference engine in the browser; MODE 'live' will fetch API_BASE with the same shapes.
// Every function here is one endpoint in src/api/contract.js (see `fn`).
import { API_BASE, LAUNCH_IXS, FEES } from './contract.js';
import { BLOCKS, byId, ENGINE } from '../data/blocks.js';
import { COINS, coinBy, stats, childrenOf, CREATORS, fakeKey, SOL_USD, curveMcapSol } from '../data/coins.js';
import { budget, evaluate, normalize } from '../engine/engine.js';
import { simulate as runSim, Curve, SUPPLY, rng } from '../engine/sim.js';

export const MODE = 'demo';
const wait = (ms = 120) => new Promise((r) => setTimeout(r, ms));
const LS = 'hookrz:launches';

async function live(path, body) {
  const res = await fetch(API_BASE + path, body ? { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) } : {});
  if (!res.ok) throw new Error(`${path} ${res.status}`);
  return res.json();
}

/** Coins launched from this browser while MODE is 'demo' (kept in localStorage, never sent anywhere). */
function localLaunches() { try { return JSON.parse(localStorage.getItem(LS) ?? '[]'); } catch { return []; } }
function allCoins() { return [...localLaunches(), ...COINS]; }

/** Shape one coin like GET /v1/coins returns it. */
export function shapeCoin(c) {
  const i = COINS.indexOf(c);
  const s = c.local ? c.stats : stats(c, i);
  return {
    ...c, ...s,
    stack: normalize(c.stack),
    creatorInfo: CREATORS[c.creator] ?? { handle: c.creator },
    phase: c.graduated ? 'graduated' : 'curve',
    families: [...new Set(c.stack.map((x) => byId[x.id]?.family))],
    budget: budget(c.stack),
    remixes: allCoins().filter((x) => x.parent === c.ticker).length,
  };
}

export const api = {
  async blocks() { if (MODE === 'live') return live('/v1/blocks'); await wait(30); return BLOCKS; },

  async coins({ sort = 'mcap', family, phase, q } = {}) {
    if (MODE === 'live') return live(`/v1/coins?${new URLSearchParams({ sort, family: family ?? '', phase: phase ?? '', q: q ?? '' })}`);
    await wait(60);
    let list = allCoins().map(shapeCoin);
    if (family) list = list.filter((c) => c.families.includes(family));
    if (phase) list = list.filter((c) => c.phase === phase);
    if (q) { const s = q.toLowerCase(); list = list.filter((c) => (c.ticker + c.name + c.creator).toLowerCase().includes(s)); }
    const key = { mcap: (c) => -c.mcapUsd, volume: (c) => -c.vol24Usd, new: (c) => c.minutesAgo, remixes: (c) => -c.remixes, change: (c) => -c.change24 }[sort] ?? ((c) => -c.mcapUsd);
    return list.sort((a, b) => key(a) - key(b));
  },

  async coin(ticker) {
    if (MODE === 'live') return live(`/v1/coins/${ticker}`);
    await wait(60);
    const c = allCoins().find((x) => x.ticker === ticker);
    return c ? shapeCoin(c) : null;
  },

  /** Recent transfers with verdicts, generated by replaying the simulator over this coin's stack. */
  async trades(ticker, { limit = 40 } = {}) {
    if (MODE === 'live') return live(`/v1/coins/${ticker}/trades?limit=${limit}`);
    const c = allCoins().find((x) => x.ticker === ticker);
    if (!c) return [];
    const sim = runSim(c.stack, { seed: [...ticker].reduce((a, ch) => a + ch.charCodeAt(0), 0) });
    return sim.log.slice(-limit).reverse().map((e, i) => ({ ...e, sig: fakeKey(9000 + i + e.wallet, ''), wallet: fakeKey(500 + e.wallet) }));
  },

  async holders(ticker) {
    if (MODE === 'live') return live(`/v1/coins/${ticker}/holders`);
    const r = rng([...ticker].reduce((a, ch) => a * 31 + ch.charCodeAt(0), 7));
    let left = 0.62;
    return Array.from({ length: 12 }, (_, i) => { const share = Math.min(left, (0.09 * r() + 0.01) / (1 + i * 0.25)); left -= share; return { wallet: fakeKey(700 + i * 3 + ticker.length), share, tier: r() < 0.3 ? 'crown' : null }; });
  },

  /** Rule-aware quote. side: buy (amount in SOL) | sell (amount in tokens). */
  async quote({ ticker, side, amount, wallet = {}, stack: stackIn, progress: progressIn, minutesAgo: minutesIn }) {
    if (MODE === 'live') return live('/v1/quote', { mint: ticker, side, amount, wallet });
    const c = allCoins().find((x) => x.ticker === ticker) ?? { stack: stackIn ?? [], progress: progressIn ?? 0.05, minutesAgo: minutesIn ?? 10 };
    const curve = new Curve();
    // warp the curve to the coin's progress
    const targetTok = curve.vTok - (curve.vTok - 279_900_191) * Math.min(0.999, c.progress);
    curve.vSol = curve.k / targetTok; curve.vTok = targetTok;
    const t = c.minutesAgo * 60;
    const ctxFor = (amt) => {
      const tokens = side === 'buy' ? curve.quoteBuy(amt, 1).out : amt;
      return {
        kind: side, amount: tokens, supply: SUPPLY, t, slot: Math.floor(t / 0.4), hour: new Date().getUTCHours(), progress: c.progress,
        priceAfter: side === 'buy' ? curve.priceAfterBuy(amt, 1) : curve.priceAfterSell(amt, 1), windowOpenPrice: curve.price,
        srcBefore: wallet.balance ?? 0, dstAfter: (wallet.balance ?? 0) + (side === 'buy' ? tokens : 0),
        isCreatorSrc: false, isCreator: false, w: { lots: wallet.lots ?? [], lastBuySlot: wallet.lastBuySlot ?? null, lastSellT: wallet.lastSellT ?? null, firstT: wallet.firstT ?? null },
        slotBuys: 0, hourSold: 0, hasPass: wallet.hasPass ?? true, gateBal: wallet.gateBal ?? 0, blocked: false,
      };
    };
    const v = evaluate(c.stack, ctxFor(amount));
    let maxAllowed = amount;
    if (!v.ok) { let lo = 0, hi = amount; for (let i = 0; i < 32; i++) { const m = (lo + hi) / 2; if (evaluate(c.stack, ctxFor(m)).ok) lo = m; else hi = m; } maxAllowed = lo; }
    const out = side === 'buy' ? curve.quoteBuy(amount, 1).out : curve.quoteSell(amount, 1).out;
    await wait(80);
    return { ok: v.ok, out, price: curve.price, priceUsd: curve.price * SOL_USD, verdicts: v.verdicts, refusedBy: v.refusedBy ?? null, code: v.code ?? null, message: v.message ?? null, maxAllowed };
  },

  async validate(stack) { if (MODE === 'live') return live('/v1/stacks/validate', { stack }); return budget(stack); },

  async simulate(stack, { seed = 7 } = {}) {
    if (MODE === 'live') return live('/v1/stacks/simulate', { stack, seed });
    await wait(10);
    return { withStack: runSim(stack, { seed }), noRules: runSim([], { seed }) };
  },

  async stacks() {
    if (MODE === 'live') return live('/v1/stacks');
    const list = await api.coins();
    return list.filter((c) => !c.parent).map((c) => ({ ...c, family: [c, ...descendantsOf(c.ticker, list)] }))
      .map((c) => ({ ...c, remixCount: c.family.length - 1, royaltiesSol: c.family.filter((x) => x.parent === c.ticker).reduce((a, x) => a + x.vol24Usd / SOL_USD * 0.01 * 0.10, 0) })) // one level up only
      .sort((a, b) => b.remixCount - a.remixCount || b.royaltiesSol - a.royaltiesSol);
  },

  async lineage(ticker) {
    if (MODE === 'live') return live(`/v1/stacks/${ticker}/lineage`);
    const list = await api.coins();
    const by = Object.fromEntries(list.map((c) => [c.ticker, c]));
    if (!by[ticker]) return null;
    const node = (t) => ({ coin: by[t], diff: diffStacks(by[by[t].parent]?.stack ?? [], by[t].stack), children: list.filter((c) => c.parent === t).map((c) => node(c.ticker)) });
    let root = by[ticker]; while (root.parent && by[root.parent]) root = by[root.parent];
    return node(root.ticker);
  },

  async draftHookscript(prompt) {
    if (MODE === 'live') return live('/v1/hookscript/draft', { prompt });
    await wait(900);
    return draftDemo(prompt);
  },

  async prepareLaunch({ meta, stack, curve = {}, creator = 'DEMO' }) {
    if (MODE === 'live') return live('/v1/launch/prepare', { meta, stack, curve, creator });
    await wait(500);
    const b = budget(stack);
    const ixs = LAUNCH_IXS.filter((x, i) => b.hasHook || i !== 3).map((x) => ({ ...x }));
    if (!b.hasHook) ixs[0] = { ...ixs[0], note: 'Extensions: MetadataPointer + TokenMetadata. No transfer hook: this stack has no Hook blocks.' };
    const bytes = 900 + normalize(stack).length * 26 + (b.hasHook ? 140 : 0);
    return { mint: fakeKey(Date.now() % 100000, 'hk'), instructions: ixs, txBytes: bytes, txLimit: 1232, rentSol: b.rentSol, launchCostSol: FEES.launchCostSol, fees: FEES, signers: ['creator', 'mint keypair'] };
  },

  /** Demo "launch": nothing is sent; the coin is saved in this browser so the rest of the site shows it. */
  async submitLaunch({ meta, stack, parent = null, prepared }) {
    if (MODE === 'live') return live('/v1/launch/submit', { signed: prepared });
    await wait(1200);
    const coin = {
      ticker: meta.ticker.toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 10), name: meta.name, creator: 'you', minutesAgo: 0, progress: 0.002, parent,
      desc: meta.desc || '', stack: normalize(stack), local: true, image: meta.image ?? null,
      stats: { mint: prepared?.mint ?? fakeKey(Date.now() % 997, 'hk'), mcapUsd: curveMcapSol(0.002) * SOL_USD, vol24Usd: 0, change24: 0, holders: 1, trades: 1, checked: 1, refused: 0, remixes: 0, royaltiesSol: 0 },
    };
    const list = localLaunches().filter((c) => c.ticker !== coin.ticker);
    try { localStorage.setItem(LS, JSON.stringify([coin, ...list].slice(0, 20))); } catch { /* private mode: coin lives for this page only */ }
    return { ok: true, ticker: coin.ticker, signature: fakeKey(Date.now() % 9973, '') };
  },

  async creator(handle) {
    if (MODE === 'live') return live(`/v1/creators/${handle}`);
    const list = await api.coins();
    const mine = list.filter((c) => c.creator === handle);
    const remixesOfMine = list.filter((c) => mine.some((m) => m.ticker === c.parent) && c.creator !== handle);
    return { handle, coins: mine, remixesOfMine, claimableSol: mine.reduce((a, c) => a + c.vol24Usd / SOL_USD * 0.005, 0), royaltiesSol: remixesOfMine.reduce((a, c) => a + c.vol24Usd / SOL_USD * 0.001, 0) };
  },

  /** Live stream (WS in live mode). Demo: replays the coin's simulated log on a timer. Returns an unsubscribe fn. */
  stream(ticker, onEvent, { speed = 1, stack: stackIn } = {}) {
    if (MODE === 'live') { const ws = new WebSocket(API_BASE.replace('http', 'ws') + `/v1/stream?mint=${ticker}`); ws.onmessage = (m) => onEvent(JSON.parse(m.data)); return () => ws.close(); }
    const c = ticker ? allCoins().find((x) => x.ticker === ticker) : null;
    const stack = c?.stack ?? stackIn ?? [];
    const sim = runSim(stack, { seed: ticker ? ticker.length * 97 : 7 });
    const log = sim.log;
    // start the replay where landed and refused transfers mix, so the first few seconds look like a normal market
    let i = Math.floor(log.length * 0.2), alive = true;
    for (let j = i; j < log.length - 8; j++) { const k = log.slice(j, j + 8).filter((e) => !e.ok).length; if (k >= 1 && k <= 2) { i = j; break; } }
    const tick = () => {
      if (!alive) return;
      const e = log[i++ % log.length];
      onEvent({ ...e, wallet: fakeKey(500 + e.wallet), sig: fakeKey(Date.now() % 100000, ''), at: Date.now() });
      setTimeout(tick, (500 + Math.random() * 1300) / speed);
    };
    setTimeout(tick, 200);
    return () => { alive = false; };
  },
};

function descendantsOf(t, list) { const out = []; const walk = (x) => list.filter((c) => c.parent === x).forEach((c) => { out.push(c); walk(c.ticker); }); walk(t); return out; }

/** What a remix changed: added / removed blocks and changed params. */
export function diffStacks(a, b) {
  const A = Object.fromEntries(normalize(a).map((s) => [s.id, s.params])), Bm = Object.fromEntries(normalize(b).map((s) => [s.id, s.params]));
  const added = Object.keys(Bm).filter((k) => !A[k]), removed = Object.keys(A).filter((k) => !Bm[k]);
  const tuned = Object.keys(Bm).filter((k) => A[k] && JSON.stringify(A[k]) !== JSON.stringify(Bm[k]));
  return { added, removed, tuned };
}

function draftDemo(prompt) {
  const p = prompt.toLowerCase();
  const n = (p.match(/(\d+(?:\.\d+)?)/) ?? [])[1] ?? '1';
  let script, ops, cu, refusalsPct;
  if (p.includes('bought') || p.includes('more than they')) {
    script = `rule "sell no more than you bought this hour"\nwhen transfer.kind == sell\nlet bought = wallet.received(window: ${n}h)\nrefuse if transfer.amount > bought\n  because "You can sell at most what you bought in the last ${n}h"`;
    ops = 9; cu = 3400; refusalsPct = 6.1;
  } else if (p.includes('weekend') || p.includes('saturday') || p.includes('sunday')) {
    script = `rule "closed on weekends"\nwhen transfer.kind in [buy, sell]\nrefuse if clock.weekday in [sat, sun]\n  because "The curve is closed on weekends"`;
    ops = 5; cu = 1300; refusalsPct = 28.4;
  } else if (p.includes('price') || p.includes('%')) {
    script = `rule "no buys after a ${n}% pump"\nwhen transfer.kind == buy\nlet move = curve.price / curve.price_at(ago: 10m) - 1\nrefuse if move > ${n} / 100\n  because "Price is up more than ${n}% in 10 minutes; buys pause"`;
    ops = 8; cu = 3900; refusalsPct = 4.2;
  } else {
    script = `rule "${prompt.slice(0, 48).replace(/"/g, "'")}"\nwhen transfer.kind == sell\nlet held = clock.now - wallet.first_receipt\nrefuse if held < ${n}h and transfer.amount > wallet.balance * 0.25\n  because "Sell at most a quarter of your bag in your first ${n}h"`;
    ops = 10; cu = 3600; refusalsPct = 7.8;
  }
  return { prompt, script, ops, cu, fuzz: { trades: 10000, refusedPct: refusalsPct, panics: 0, maxCu: Math.round(cu * 1.18) }, reviewed: false };
}
