// The only door between the UI and the backend. MODE 'demo' answers from seeded data + the
// reference engine in the browser; MODE 'live' fetches the hookrz server (server/) with the same shapes.
// Live mode is opt-in: build or serve the site with VITE_API_BASE set (see web/.env.example).
// Every function here is one endpoint in src/api/contract.js (see `fn`).
import { LAUNCH_IXS, FEES } from './contract.js';
import { BLOCKS, byId, ENGINE } from '../data/blocks.js';
import { COINS, coinBy, stats, childrenOf, CREATORS, fakeKey, SOL_USD, curveMcapSol } from '../data/coins.js';
import { budget, evaluate, normalize } from '../engine/engine.js';
import { simulate as runSim, Curve, SUPPLY, rng } from '../engine/sim.js';
import { feeSplit, feeRouting, lockedLpPctOf } from '../engine/fees.js';

const ENV_API = (typeof import.meta !== 'undefined' && import.meta.env?.VITE_API_BASE) || '';
export const API_BASE = ENV_API === 'same-origin' ? (typeof location !== 'undefined' ? location.origin : '') : ENV_API.replace(/\/$/, '');
export const MODE = API_BASE ? 'live' : 'demo';
const wait = (ms = 120) => new Promise((r) => setTimeout(r, ms));
const LS = 'hookrz:launches';

async function live(path, body) {
  const res = await fetch(API_BASE + path, body ? { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) } : {});
  if (!res.ok) {
    let j = null; try { j = await res.json(); } catch { /* not JSON */ }
    const e = new Error(j?.message ?? `${path} ${res.status}`);
    Object.assign(e, { status: res.status, code: j?.error, details: j?.details });
    throw e;
  }
  return res.json();
}
/** GET that answers null on 404 (a ticker nobody has launched yet). */
async function liveOrNull(path) {
  try { return await live(path); } catch (e) { if (e.status === 404) return null; throw e; }
}

// ───────── live mode: the wallet signs and sends; the server builds, relays and indexes ─────────
const b64bytes = (b64) => Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
/** wallet.js handles call tx.serialize(); a prepared transaction is already serialized bytes. */
const wireTx = (b64) => { const bytes = b64bytes(b64); return { serialize: () => bytes }; };
async function walletHandle() {
  const w = await import('../wallet/wallet.js');
  const h = await w.connect();
  return { h, address: w.address };
}
/** Waits until the server has the transaction (landed or refused). */
async function waitTx(sig, ms = 90_000) {
  const end = Date.now() + ms;
  for (;;) {
    const r = await liveOrNull(`/v1/tx/${sig}`);
    if (r) return r;
    if (Date.now() > end) throw new Error('The transaction was not confirmed in time. Check your wallet before trying again.');
    await wait(900);
  }
}
async function signSendWait(h, b64) {
  const sig = await h.signAndSend(wireTx(b64));
  const rec = await waitTx(sig);
  return { sig, rec };
}

/** Coins launched from this browser while MODE is 'demo' (kept in localStorage, never sent anywhere). */
function localLaunches() { try { return JSON.parse(localStorage.getItem(LS) ?? '[]'); } catch { return []; } }
function allCoins() { return [...localLaunches(), ...COINS]; }

/** Shape one coin like GET /v1/coins returns it. */
export function shapeCoin(c) {
  const i = COINS.indexOf(c);
  const s = c.local ? c.stats : stats(c, i);
  return {
    ...c, ...s,
    stack: normalize(c.stack),
    creatorInfo: CREATORS[c.creator] ?? { handle: c.creator },
    phase: c.graduated ? 'graduated' : 'curve',
    families: [...new Set(c.stack.map((x) => byId[x.id]?.family))],
    budget: budget(c.stack),
    remixes: allCoins().filter((x) => x.parent === c.ticker).length,
  };
}

export const api = {
  // the catalog is code shared with the engine (check/format functions), so it is read locally in both modes
  async blocks() { await wait(30); return BLOCKS; },

  async coins({ sort = 'mcap', family, phase, q } = {}) {
    if (MODE === 'live') return live(`/v1/coins?${new URLSearchParams({ sort, family: family ?? '', phase: phase ?? '', q: q ?? '' })}`);
    await wait(60);
    let list = allCoins().map(shapeCoin);
    if (family) list = list.filter((c) => c.families.includes(family));
    if (phase) list = list.filter((c) => c.phase === phase);
    if (q) { const s = q.toLowerCase(); list = list.filter((c) => (c.ticker + c.name + c.creator).toLowerCase().includes(s)); }
    const key = { mcap: (c) => -c.mcapUsd, volume: (c) => -c.vol24Usd, new: (c) => c.minutesAgo, remixes: (c) => -c.remixes, change: (c) => -c.change24 }[sort] ?? ((c) => -c.mcapUsd);
    return list.sort((a, b) => key(a) - key(b));
  },

  async coin(ticker) {
    if (MODE === 'live') return liveOrNull(`/v1/coins/${encodeURIComponent(ticker)}?optional=1`);
    await wait(60);
    const c = allCoins().find((x) => x.ticker === ticker);
    return c ? shapeCoin(c) : null;
  },

  /** Recent transfers with verdicts, generated by replaying the simulator over this coin's stack. */
  async trades(ticker, { limit = 40 } = {}) {
    if (MODE === 'live') return live(`/v1/coins/${ticker}/trades?limit=${limit}`);
    const c = allCoins().find((x) => x.ticker === ticker);
    if (!c) return [];
    const sim = runSim(c.stack, { seed: [...ticker].reduce((a, ch) => a + ch.charCodeAt(0), 0) });
    return sim.log.slice(-limit).reverse().map((e, i) => ({ ...e, sig: fakeKey(9000 + i + e.wallet, ''), wallet: fakeKey(500 + e.wallet) }));
  },

  async holders(ticker) {
    if (MODE === 'live') return live(`/v1/coins/${ticker}/holders`);
    const r = rng([...ticker].reduce((a, ch) => a * 31 + ch.charCodeAt(0), 7));
    let left = 0.62;
    return Array.from({ length: 12 }, (_, i) => { const share = Math.min(left, (0.09 * r() + 0.01) / (1 + i * 0.25)); left -= share; return { wallet: fakeKey(700 + i * 3 + ticker.length), share, tier: r() < 0.3 ? 'crown' : null }; });
  },

  /** Rule-aware quote. side: buy (amount in SOL) | sell (amount in tokens). */
  async quote({ ticker, side, amount, wallet = {}, stack: stackIn, progress: progressIn, minutesAgo: minutesIn }) {
    if (MODE === 'live') {
      // the server reads the wallet's real state (balance, Wallet record) from chain; send its address
      const w = await import('../wallet/wallet.js');
      return live('/v1/quote', { mint: ticker, side, amount, wallet: w.address ?? null });
    }
    const c = allCoins().find((x) => x.ticker === ticker) ?? { stack: stackIn ?? [], progress: progressIn ?? 0.05, minutesAgo: minutesIn ?? 10 };
    const curve = new Curve();
    // warp the curve to the coin's progress
    const targetTok = curve.vTok - (curve.vTok - 279_900_191) * Math.min(0.999, c.progress);
    curve.vSol = curve.k / targetTok; curve.vTok = targetTok;
    const t = c.minutesAgo * 60;
    const ctxFor = (amt) => {
      const tokens = side === 'buy' ? curve.quoteBuy(amt, 1).out : amt;
      return {
        kind: side, amount: tokens, supply: SUPPLY, t, slot: Math.floor(t / 0.4), hour: new Date().getUTCHours(), progress: c.progress,
        priceAfter: side === 'buy' ? curve.priceAfterBuy(amt, 1) : curve.priceAfterSell(amt, 1), windowOpenPrice: curve.price,
        srcBefore: wallet.balance ?? 0, dstAfter: (wallet.balance ?? 0) + (side === 'buy' ? tokens : 0),
        isCreatorSrc: false, isCreator: false, w: { lots: wallet.lots ?? [], lastBuySlot: wallet.lastBuySlot ?? null, lastSellT: wallet.lastSellT ?? null, firstT: wallet.firstT ?? null },
        slotBuys: 0, hourSold: 0, hasPass: wallet.hasPass ?? true, gateBal: wallet.gateBal ?? 0, blocked: false,
      };
    };
    const v = evaluate(c.stack, ctxFor(amount));
    let maxAllowed = amount;
    if (!v.ok) { let lo = 0, hi = amount; for (let i = 0; i < 32; i++) { const m = (lo + hi) / 2; if (evaluate(c.stack, ctxFor(m)).ok) lo = m; else hi = m; } maxAllowed = lo; }
    const out = side === 'buy' ? curve.quoteBuy(amount, 1).out : curve.quoteSell(amount, 1).out;
    await wait(80);
    return { ok: v.ok, out, price: curve.price, priceUsd: curve.price * SOL_USD, verdicts: v.verdicts, refusedBy: v.refusedBy ?? null, code: v.code ?? null, message: v.message ?? null, maxAllowed };
  },

  async validate(stack) { if (MODE === 'live') return live('/v1/stacks/validate', { stack }); return budget(stack); },

  async simulate(stack, { seed = 7 } = {}) {
    if (MODE === 'live') return live('/v1/stacks/simulate', { stack, seed });
    await wait(10);
    return { withStack: runSim(stack, { seed }), noRules: runSim([], { seed }) };
  },

  async stacks() {
    if (MODE === 'live') return live('/v1/stacks');
    const list = await api.coins();
    return list.filter((c) => !c.parent).map((c) => ({ ...c, family: [c, ...descendantsOf(c.ticker, list)] }))
      .map((c) => ({ ...c, remixCount: c.family.length - 1 }))
      .sort((a, b) => b.remixCount - a.remixCount || b.vol24Usd - a.vol24Usd);
  },

  async lineage(ticker) {
    if (MODE === 'live') return live(`/v1/stacks/${ticker}/lineage`);
    const list = await api.coins();
    const by = Object.fromEntries(list.map((c) => [c.ticker, c]));
    if (!by[ticker]) return null;
    const node = (t) => ({ coin: by[t], diff: diffStacks(by[by[t].parent]?.stack ?? [], by[t].stack), children: list.filter((c) => c.parent === t).map((c) => node(c.ticker)) });
    let root = by[ticker]; while (root.parent && by[root.parent]) root = by[root.parent];
    return node(root.ticker);
  },

  /**
   * English → Hookscript. Every draft is compiled, fuzzed against generated trades and honeypot-checked before it comes
   * back: { ok, prompt, script, bytecodeHex, bytes, ops, cu, fuzz{trades, refusedPct, panics, errors, maxCu, avgCu, …},
   * honeypot{ok, notes, …}, warnings, errors, abi, provider, template, reviewed:false }.
   * Live: the server's drafter (Claude when it has an API key, else the offline drafter). Otherwise: the same offline
   * drafter, in a worker on this page.
   */
  async draftHookscript(prompt) {
    if (MODE === 'live') return live('/v1/hookscript/draft', { prompt });
    const hs = await import('../hookscript/hs.js');
    return hs.draftOffline(prompt);
  },

  /** Compile Hookscript source on this page: { ok, size, ops, cu, hex, abi, warnings } or { ok:false, errors[{line, col, message, hint}] }. */
  async compileHookscript(source) {
    const hs = await import('../hookscript/hs.js');
    return hs.compileSource(source);
  },

  /** Compile + fuzz + honeypot check (the checks a script must pass to launch): { source, compile, check }. */
  async checkHookscript(source) {
    const hs = await import('../hookscript/hs.js');
    return hs.checkSource(source);
  },

  /**
   * marks: Blocklist / Allowlist Phase entries written in the launch transaction, [{ owner, blocked?, pass? }] (3 fit
   * beside a creator buy). The answer's curve.feeSplit is the fee routing the coin's DBC config gets (web/src/engine/fees.js).
   */
  async prepareLaunch({ meta, stack, curve = {}, creator = 'DEMO', parent = null, mint = null, marks = [] }) {
    if (MODE === 'live') return live('/v1/launch/prepare', { meta, stack, curve, creator: creator === 'DEMO' ? null : creator, parent, mint, script: scriptOf(stack), marks: marksOut(marks) });
    await wait(500);
    const abi = await scriptAbiOf(stack);
    const b = budget(stack);
    const ixs = LAUNCH_IXS.filter((x, i) => b.hasHook || i !== 3).map((x) => ({ ...x }));
    if (!b.hasHook) ixs[0] = { ...ixs[0], note: 'Extensions: MetadataPointer + TokenMetadata. No transfer hook: this stack has no Hook blocks.' };
    const bytes = 900 + normalize(stack).length * 26 + (b.hasHook ? 140 : 0);
    const nMarks = marksOut(marks).length;
    return { mint: fakeKey(Date.now() % 100000, 'hk'), instructions: ixs, txBytes: bytes + nMarks * 70, txLimit: 1232, rentSol: b.rentSol, launchCostSol: FEES.launchCostSol, fees: FEES, signers: ['creator', 'mint keypair'], curve: { feeSplit: feeSplit(stack, abi) }, marks: nMarks };
  },

  /** Demo "launch": nothing is sent; the coin is saved in this browser so the rest of the site shows it. */
  async submitLaunch({ meta, stack, parent = null, prepared, marks = [] }) {
    if (MODE === 'live') {
      // Rebuild for the connected wallet (same mint, fresh blockhash, parent stack and launch marks attached), then the
      // wallet signs and sends each transaction in order; the server confirms and indexes the coin.
      const { h, address } = await walletHandle();
      const P = await live('/v1/launch/prepare', { meta, stack, creator: address, parent, mint: prepared?.mint ?? null, script: scriptOf(stack), marks: marksOut(marks) });
      const signatures = [];
      for (const t of P.transactions) {
        const { sig, rec } = await signSendWait(h, t.base64);
        if (!rec.ok) throw new Error(`Launch transaction refused (${rec.code ?? rec.error}). Nothing after it was sent.`);
        signatures.push(sig);
      }
      return live('/v1/launch/submit', { mint: P.mint, signatures, manifest: prepared?.manifest ?? null, manifestSignature: prepared?.manifestSignature ?? null });
    }
    await wait(1200);
    const coin = {
      ticker: meta.ticker.toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 10), name: meta.name, creator: 'you', minutesAgo: 0, progress: 0.002, parent,
      desc: meta.desc || '', stack: normalize(stack), local: true, image: meta.image ?? null,
      // the wallet that signed the launch (it edits the coin's lists), when it was launched, and the lists written at launch
      creatorWallet: prepared?.creator ?? null, launchTs: Math.floor(Date.now() / 1000), marks: marksOut(marks),
      stats: { mint: null, // nothing went on chain in this mode, so there is no contract address to show
       mcapUsd: curveMcapSol(0.002) * SOL_USD, vol24Usd: 0, change24: 0, holders: 1, trades: 1, checked: 1, refused: 0, remixes: 0 },
    };
    const list = localLaunches().filter((c) => c.ticker !== coin.ticker);
    try { localStorage.setItem(LS, JSON.stringify([coin, ...list].slice(0, 20))); } catch { /* private mode: coin lives for this page only */ }
    return { ok: true, ticker: coin.ticker, signature: fakeKey(Date.now() % 9973, '') };
  },

  /** Unsigned swap for the connected wallet: hook accounts resolved, Wallet record opened if the stack needs one. */
  async prepareTrade({ ticker, side, amount, wallet, slippageBps = 300 }) {
    if (MODE === 'live') return live('/v1/trade/prepare', { mint: ticker, side, amount, wallet, slippageBps });
    await wait(200);
    return { mint: null, ticker, side, amount, transaction: null, demo: true };
  },

  /** Prepare → the wallet signs and sends → the chain's verdict. Demo: a simulated landing. */
  async trade({ ticker, side, amount, slippageBps = 300 }) {
    if (MODE === 'live') {
      const { h, address } = await walletHandle();
      const P = await live('/v1/trade/prepare', { mint: ticker, side, amount, wallet: address, slippageBps });
      const { sig, rec } = await signSendWait(h, P.transaction);
      // message: the refusal as the trader reads it (a Hookscript reason is formatted by the server from the coin's bytecode)
      return { ok: rec.ok, signature: sig, code: rec.code ?? null, error: rec.error ?? null, message: rec.explain?.msg ?? null, by: rec.explain?.by ?? null, slot: rec.slot, openedRecords: P.openedRecords ?? [] };
    }
    await wait(1300 + Math.random() * 700);
    return { ok: true, signature: fakeKey(Date.now() % 99991, ''), code: null, error: null, demo: true };
  },

  /** GET /v1/health: { ok, mode: fork | devnet | mainnet, slot, unix, … }. Demo: nothing is on a chain, so mode is null. */
  health() {
    if (MODE !== 'live') return Promise.resolve({ ok: true, mode: null, unix: Math.floor(Date.now() / 1000) });
    healthP ??= live('/v1/health').catch((e) => { healthP = null; throw e; });
    return healthP;
  },

  /**
   * A coin's fee routing and keeper ledger (GET /v1/coins/:mint/keeper): routing, totals, rules[{ key, id, label,
   * sharePct, kind, to, paidSol, burnedSol, burnedTokens, owedSol, note }], creator, actions[{ kind, rule, ok, sig, dest,
   * lamports, tokens, detail, at }], lastRound. Demo: the same shape for a coin launched in this browser, with nothing
   * claimed (nothing it does reaches a chain, so there is nothing to pay).
   */
  async coinKeeper(ticker) {
    if (MODE === 'live') return live(`/v1/coins/${encodeURIComponent(ticker)}/keeper`);
    await wait(60);
    const c = allCoins().find((x) => x.ticker === ticker);
    if (!c) return null;
    const R = feeRouting(c.stack);
    const zero = { accruedSol: 0, paidSol: 0, burnedSol: 0, burnedTokens: 0, owedSol: 0, lastAt: null, note: null };
    return {
      mint: null, ticker, keeper: R.keeper, platform: null,
      routing: {
        creatorTradingFeePct: R.creatorTradingFeePercentage, platformClaimPct: 100 - R.creatorTradingFeePercentage, hookrzPct: 50,
        routedPct: R.shareBps / 200, keeperShareOfCreatorPct: R.shareBps / 100, creatorPassThrough: !!R.sniper,
        sniper: R.sniper ? { startPct: R.sniper.startBps / 100, endPct: 1, seconds: R.sniper.seconds } : null,
        afterGraduation: { partnerLockedLpPct: R.partnerLockedLpPct, lockedLpPct: lockedLpPctOf(c.stack) },
      },
      totals: { claimedSol: 0, keptSol: 0, paidSol: 0, burnedSol: 0, burnedTokens: 0, owedSol: 0, creatorPaidSol: 0, creatorOwedSol: 0 },
      rules: [
        ...(R.sniper ? [{ key: 'sniper-fee-burn', id: 'sniper-fee-burn', label: byId['sniper-fee-burn'].name, sharePct: null, kind: 'burn', mode: null, to: null }] : []),
        ...R.shares.map((x) => ({ key: x.key, id: x.id, label: x.label, sharePct: x.bps / 100, kind: x.kind, mode: x.mode ?? null, to: x.id === 'tithe' ? x.params?.to || null : x.to ?? null })),
      ].map((r) => ({ ...r, ...zero })),
      creator: { wallet: c.creatorWallet ?? null, ...zero }, state: {}, lastRound: null, lastClaimAt: null, lastError: null, actions: [],
    };
  },

  /** GET /v1/keeper: the public keeper's loop and every keeper coin's totals. Demo: no keeper runs in a browser. */
  async keeper() {
    if (MODE === 'live') return live('/v1/keeper');
    return { running: false, intervalMs: 0, lastTick: null, platform: null, coins: [], actions: [] };
  },

  /** The coin's Blocklist and Allowlist passes: [{ owner, blocked, pass, flags }] (live: read from chain). */
  async marks(ticker) {
    if (MODE === 'live') return live(`/v1/coins/${encodeURIComponent(ticker)}/marks`);
    await wait(60);
    const c = localLaunches().find((x) => x.ticker === ticker);
    return (c?.marks ?? []).map((m) => ({ owner: m.owner, blocked: !!m.blocked, pass: !!m.pass, flags: (m.blocked ? 1 : 0) | (m.pass ? 2 : 0) }));
  },

  /**
   * Unsigned set_mark transactions for the creator (POST /v1/coins/:mint/marks/prepare): body { creator, marks:
   * [{ owner, blocked?, pass? }] } (an omitted field keeps the owner's bit) → { marks (changed), blocklistOpen,
   * transactions[{ label, bytes, base64 }] }.
   */
  async prepareMarks({ ticker, creator, marks }) {
    if (MODE === 'live') return live(`/v1/coins/${encodeURIComponent(ticker)}/marks/prepare`, { creator, marks });
    await wait(150);
    return demoMarks(ticker, creator, marks, { write: false });
  },

  /** The creator edits the lists: prepare → the wallet signs and sends each transaction → confirmed. Demo: saved in this browser. */
  async setMarks({ ticker, marks }) {
    if (MODE === 'live') {
      const { h, address } = await walletHandle();
      const P = await live(`/v1/coins/${encodeURIComponent(ticker)}/marks/prepare`, { creator: address, marks });
      const signatures = [];
      for (const t of P.transactions) {
        const { sig, rec } = await signSendWait(h, t.base64);
        if (!rec.ok) throw Object.assign(new Error(`The change was refused on chain (${rec.code ?? rec.error}). Nothing after it was sent.`), { code: rec.code ?? null, signatures });
        signatures.push(sig);
      }
      return { ok: true, signatures, marks: P.marks, blocklistOpen: P.blocklistOpen };
    }
    const w = await import('../wallet/wallet.js');
    await w.connect();
    await wait(900);
    return demoMarks(ticker, w.address, marks, { write: true });
  },

  async creator(handle) {
    if (MODE === 'live') return live(`/v1/creators/${handle}`);
    const list = await api.coins();
    const mine = list.filter((c) => c.creator === handle);
    const remixesOfMine = list.filter((c) => mine.some((m) => m.ticker === c.parent) && c.creator !== handle);
    return { handle, coins: mine, remixesOfMine, claimableSol: mine.reduce((a, c) => a + c.vol24Usd / SOL_USD * 0.005, 0) };
  },

  /** Live stream (WS in live mode). Demo: replays the coin's simulated log on a timer. Returns an unsubscribe fn. */
  stream(ticker, onEvent, { speed = 1, stack: stackIn } = {}) {
    // live: a coin's real transfers over SSE. Without a ticker the caller animates a stack (the build rack), which stays simulated.
    if (MODE === 'live' && ticker) {
      const es = new EventSource(`${API_BASE}/v1/stream?mint=${encodeURIComponent(ticker)}`);
      es.onmessage = (m) => { try { const e = JSON.parse(m.data); if (e.type === 'trade') onEvent(e); } catch { /* keep-alive */ } };
      return () => es.close();
    }
    const c = ticker ? allCoins().find((x) => x.ticker === ticker) : null;
    const stack = c?.stack ?? stackIn ?? [];
    const sim = runSim(stack, { seed: ticker ? ticker.length * 97 : 7 });
    const log = sim.log;
    // start the replay where landed and refused transfers mix, so the first few seconds look like a normal market
    let i = Math.floor(log.length * 0.2), alive = true;
    for (let j = i; j < log.length - 8; j++) { const k = log.slice(j, j + 8).filter((e) => !e.ok).length; if (k >= 1 && k <= 2) { i = j; break; } }
    const tick = () => {
      if (!alive) return;
      const e = log[i++ % log.length];
      onEvent({ ...e, wallet: fakeKey(500 + e.wallet), sig: fakeKey(Date.now() % 100000, ''), at: Date.now() });
      setTimeout(tick, (500 + Math.random() * 1300) / speed);
    };
    setTimeout(tick, 200);
    return () => { alive = false; };
  },
};

function descendantsOf(t, list) { const out = []; const walk = (x) => list.filter((c) => c.parent === x).forEach((c) => { out.push(c); walk(c.ticker); }); walk(t); return out; }

/** What a remix changed: added / removed blocks and changed params. */
export function diffStacks(a, b) {
  const A = Object.fromEntries(normalize(a).map((s) => [s.id, s.params])), Bm = Object.fromEntries(normalize(b).map((s) => [s.id, s.params]));
  const added = Object.keys(Bm).filter((k) => !A[k]), removed = Object.keys(A).filter((k) => !Bm[k]);
  const tuned = Object.keys(Bm).filter((k) => A[k] && JSON.stringify(A[k]) !== JSON.stringify(Bm[k]));
  return { added, removed, tuned };
}

/** The Custom block's Hookscript source (the server compiles it and runs the same checks before it builds the launch). */
function scriptOf(stack) {
  const src = stack?.find((s) => s.id === 'custom')?.params?.script;
  return src ? { source: src } : null;
}

let healthP = null;

/** Launch marks as the server takes them: one per owner (a wallet both blocked and given a pass is one mark). */
function marksOut(list) {
  const by = new Map();
  for (const m of list ?? []) {
    const owner = String(m.owner ?? '').trim();
    if (!owner) continue;
    const cur = by.get(owner) ?? { owner };
    if (m.blocked) cur.blocked = true;
    if (m.pass) cur.pass = true;
    by.set(owner, cur);
  }
  return [...by.values()].filter((m) => m.blocked || m.pass);
}

/** The Hookscript ABI the server will compile from the Custom block (its payout lines change the fee split). */
async function scriptAbiOf(stack) {
  const src = scriptOf(stack)?.source;
  if (!src) return null;
  try { const hs = await import('../hookscript/hs.js'); const c = await hs.compileSource(src); return c?.ok ? c.abi ?? null : null; } catch { return null; }
}

/** Whether a Blocklist can still change (the engine's rule): open in the launch slot, then until `lockAt`. */
export function blocklistOpen(coin, unixNow = Math.floor(Date.now() / 1000)) {
  const s = normalize(coin?.stack ?? []).find((x) => x.id === 'blocklist');
  if (!s || coin.phase === 'graduated' || coin.graduated) return false;
  const at = s.params.lockAt;
  if (at === 'at graduation') return true;
  if (at === 'after 24h') return coin.launchTs != null && unixNow - coin.launchTs < 86400;
  return false; // immediately: only the launch transaction could write it
}

/** Demo marks: the same checks as the server's prepare, applied to the coin saved in this browser. */
function demoMarks(ticker, creator, marks, { write }) {
  const all = localLaunches();
  const c = all.find((x) => x.ticker === ticker);
  const fail = (code, message, status = 400) => { throw Object.assign(new Error(message), { code, status }); };
  if (!c) fail('NOT_FOUND', `No coin ${ticker}`, 404);
  if (!creator || creator !== c.creatorWallet) fail('NOT_CREATOR', "Only the coin's creator can edit its blocklist and passes");
  const ids = c.stack.map((x) => x.id);
  const open = blocklistOpen(shapeCoin(c));
  const cur = new Map((c.marks ?? []).map((m) => [m.owner, { ...m }]));
  const changed = [];
  for (const m of marks ?? []) {
    if (m.blocked !== undefined && !ids.includes('blocklist')) fail('NO_BLOCKLIST', 'This coin has no Blocklist');
    if (m.pass !== undefined && !ids.includes('allowlist-phase')) fail('NO_ALLOWLIST', 'This coin has no Allowlist Phase');
    const was = cur.get(m.owner) ?? { owner: m.owner, blocked: false, pass: false };
    const next = { owner: m.owner, blocked: m.blocked ?? !!was.blocked, pass: m.pass ?? !!was.pass };
    if (next.blocked !== !!was.blocked && !open) fail('BLOCKLIST_FROZEN', "The blocklist is frozen: it can't change any more");
    if (next.blocked === !!was.blocked && next.pass === !!was.pass) continue;
    cur.set(m.owner, next);
    changed.push({ owner: m.owner, flags: (next.blocked ? 1 : 0) | (next.pass ? 2 : 0) });
  }
  if (write) {
    c.marks = [...cur.values()].filter((m) => m.blocked || m.pass);
    try { localStorage.setItem(LS, JSON.stringify(all)); } catch { /* private mode */ }
  }
  return { mint: null, ticker, marks: changed, blocklistOpen: open, transactions: [] };
}
