//! Parity: every vector in vectors/*.json (generated by vectors/gen.mjs from web/src/engine/engine.js)
//! must get the same verdict from the program's pure block logic.

use hookrz_engine::blocks::{self, Ctx, Kind, Lot, WalletView, LOTS, PARAMS};
use serde_json::Value;
use std::{collections::BTreeMap, fs, path::Path};

fn num<T: std::str::FromStr>(v: &Value) -> T
where
    T::Err: std::fmt::Debug,
{
    match v {
        Value::String(s) => s.parse().unwrap(),
        Value::Number(n) => n.to_string().parse().unwrap(),
        _ => panic!("not a number: {v}"),
    }
}
fn opt<T: std::str::FromStr>(v: &Value) -> Option<T>
where
    T::Err: std::fmt::Debug,
{
    if v.is_null() {
        None
    } else {
        Some(num(v))
    }
}

fn ctx_of(c: &Value) -> Ctx {
    let kind = match c["kind"].as_str().unwrap() {
        "buy" => Kind::Buy,
        "sell" => Kind::Sell,
        _ => Kind::Send,
    };
    let mut lots = [Lot::default(); LOTS];
    let src = c["w"]["lots"].as_array().unwrap();
    assert!(src.len() <= LOTS);
    for (l, s) in lots.iter_mut().zip(src) {
        l.t = num(&s["t"]);
        l.amount = num(&s["amt"]);
    }
    Ctx {
        kind,
        amount: num(&c["amount"]),
        supply: num(&c["supply"]),
        t: num(&c["t"]),
        slot: num(&c["slot"]),
        hour: num(&c["hour"]),
        quote_reserve: num(&c["quoteReserve"]),
        threshold: num(&c["threshold"]),
        sqrt_after: num(&c["sqrtAfter"]),
        sqrt_open: num(&c["sqrtOpen"]),
        src_before: num(&c["srcBefore"]),
        dst_after: num(&c["dstAfter"]),
        is_creator: c["isCreator"].as_bool().unwrap(),
        is_creator_src: c["isCreatorSrc"].as_bool().unwrap(),
        w: WalletView {
            lots,
            last_buy_slot: opt(&c["w"]["lastBuySlot"]),
            last_sell_t: opt(&c["w"]["lastSellT"]),
            first_t: opt(&c["w"]["firstT"]),
        },
        slot_buys: num(&c["slotBuys"]),
        creator_base: num(&c["creatorBase"]),
    }
}

fn hex(s: &str) -> [u8; PARAMS] {
    let mut out = [0u8; PARAMS];
    for (i, o) in out.iter_mut().enumerate() {
        *o = u8::from_str_radix(&s[i * 2..i * 2 + 2], 16).unwrap();
    }
    out
}

#[test]
fn rust_blocks_match_the_reference_engine() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("vectors");
    let mut files: Vec<_> = fs::read_dir(&dir).unwrap().map(|e| e.unwrap().path()).filter(|p| p.extension().is_some_and(|e| e == "json")).collect();
    files.sort();
    assert!(!files.is_empty(), "no vectors: run `node vectors/gen.mjs`");
    let mut report = BTreeMap::new();
    let mut failures = Vec::new();
    for f in &files {
        let list: Vec<Value> = serde_json::from_str(&fs::read_to_string(f).unwrap()).unwrap();
        let (mut pass, mut fail) = (0usize, 0usize);
        for v in &list {
            let slots: Vec<(u16, [u8; PARAMS])> = v["slots"].as_array().unwrap().iter().map(|s| (num(&s["id"]), hex(s["params"].as_str().unwrap()))).collect();
            // Every packed slot is a valid init_stack slot (engine.test.mjs uses some off-range params).
            let reference = f.file_stem().is_some_and(|s| s == "reference-tests");
            for (id, p) in slots.iter().filter(|_| !reference) {
                assert!(blocks::valid_params(*id, p), "{}: params of block {} out of range: {:?}", v["name"], id, p);
            }
            let got = blocks::evaluate(&slots, &ctx_of(&v["ctx"]));
            let e = &v["expect"];
            let want = if e["ok"].as_bool().unwrap() { None } else { Some((e["index"].as_u64().unwrap() as usize, e["code"].as_u64().unwrap() as u32)) };
            if got == want {
                pass += 1;
            } else {
                fail += 1;
                if failures.len() < 20 {
                    failures.push(format!("{} / {}: got {:?}, want {:?}\n  ctx {}", f.file_name().unwrap().to_string_lossy(), v["name"], got, want, v["ctx"]));
                }
            }
        }
        report.insert(f.file_stem().unwrap().to_string_lossy().to_string(), (pass, fail));
    }
    let total: (usize, usize) = report.values().fold((0, 0), |a, b| (a.0 + b.0, a.1 + b.1));
    for (k, (p, f)) in &report {
        println!("{k:>18}: {p:>5} pass {f:>3} fail");
    }
    println!("{:>18}: {:>5} pass {:>3} fail", "TOTAL", total.0, total.1);
    assert!(failures.is_empty(), "parity failures:\n{}", failures.join("\n"));
}
